.ifndef INC_ASM09
.equ INC_ASM09, 0

// Public Interface
.extern off_806DA68

// Forward Reference
.extern ho_806D928
.extern off_806D93C
.extern jt_806D940
.extern nullsub_73
.extern nullsub_74
.extern nullsub_75
.extern nullsub_76
.extern nullsub_77
.extern sub_806D95E
.extern off_806D974
.extern off_806D978
.extern dword_806D98C
.extern dword_806D9A4
.extern dword_806D9D0
.extern dword_806D9FC
.extern dword_806DA28
.extern dword_806DA90
.extern dword_806DAA0
.extern dword_806DAB0
.extern dword_806DAC0


.endif // INC_ASM09
