.ifndef INC_ASM07
.equ INC_ASM07, 0

// Public Interface
.extern off_8069638

// Forward Reference
.extern sub_8069450
.extern off_80694A8
.extern off_80694AC
.extern off_80694B0
.extern off_80694B4
.extern dword_80694BC
.extern sub_80694CA
.extern off_80694D8
.extern off_80694DC
.extern off_80694E4
.extern off_80694F0
.extern sub_80694FC
.extern off_8069538
.extern off_806953C
.extern off_806955C
.extern off_8069560
.extern off_8069568
.extern sub_806958C
.extern off_80695A0
.extern off_80695A4
.extern nullsub_71
.extern nullsub_72
.extern sub_80695B0
.extern off_80695C4
.extern off_80695C8
.extern dword_80695D0
.extern dword_80695FC


.endif // INC_ASM07
