.ifndef INC_ASM08
.equ INC_ASM08, 0

// Public Interface
.extern sub_806A9C4
.extern off_806AB28

// Forward Reference
.extern sub_806A87C
.extern off_806A8D4
.extern off_806A8D8
.extern off_806A8DC
.extern off_806A8E0
.extern dword_806A8F0
.extern sub_806A91E
.extern off_806A92C
.extern off_806A930
.extern off_806A940
.extern off_806A964
.extern off_806A988
.extern off_806A9AC
.extern off_806AA00
.extern off_806AA04
.extern off_806AA44
.extern off_806AA48
.extern off_806AA58
.extern off_806AA7C
.extern loc_806AAA0
.extern off_806AAB4
.extern off_806AAB8
.extern locret_806AAC8
.extern locret_806AACA
.extern locret_806AACC
.extern locret_806AACE
.extern sub_806AAD0
.extern off_806AAE4
.extern off_806AAE8
.extern dword_806AAF8
.extern dword_806AAFC
.extern dword_806AB00
.extern dword_806AB04


.endif // INC_ASM08
