.ifndef INC_ASM12
.equ INC_ASM12, 0

// Public Interface

// Forward Reference
.extern dead_80758A4
.extern off_80758FC
.extern off_8075900
.extern off_8075904
.extern off_8075908
.extern dword_8075948
.extern sub_8075A0C
.extern off_8075A48
.extern off_8075A4C
.extern off_8075B4C
.extern off_8075B50
.extern off_8075B90
.extern loc_8075BB4
.extern off_8075BC8
.extern off_8075BCC
.extern locret_8075C0C
.extern sub_8075C0E
.extern off_8075C24
.extern off_8075C28


.endif // INC_ASM12
