.ifndef INC_ASM15
.equ INC_ASM15, 0

// Public Interface
.extern sub_807CB92
.extern sub_807CBEC
.extern off_807CD54

// Forward Reference
.extern off_807CBA0
.extern pt_807CBA4
.extern off_807CBB0
.extern off_807CBC4
.extern off_807CBD8
.extern off_807CC28
.extern off_807CC2C
.extern off_807CC5C
.extern off_807CC60
.extern off_807CC6C
.extern loc_807CC90
.extern off_807CCA4
.extern off_807CCA8
.extern locret_807CCB4
.extern locret_807CCB6
.extern locret_807CCB8
.extern sub_807CCBA
.extern off_807CCD0
.extern off_807CCD4
.extern dword_807CCE0
.extern dword_807CCF8
.extern dword_807CD24


.endif // INC_ASM15
