.ifndef INC_ASM11
.equ INC_ASM11, 0

// Public Interface

// Forward Reference
.extern sub_8073910
.extern off_8073968
.extern off_807396C
.extern off_8073970
.extern off_8073974
.extern dword_80739A4
.extern sub_8073A30
.extern off_8073A6C
.extern off_8073A70
.extern off_8073B30
.extern off_8073B34
.extern off_8073B64
.extern sub_8073B88
.extern off_8073B9C
.extern jt_nullsub_8073BA0
.extern nullsub_78
.extern sub_8073BD2
.extern off_8073BE8
.extern off_8073BEC


.endif // INC_ASM11
