.ifndef INC_ASM22
.equ INC_ASM22, 0

/* Public Interface */
.extern sub_808EC76
.extern sub_808F45C


/* External Symbols */
.include "asm03.inc"
// .extern sub_80511C0

.include "asm13.inc"
// .extern sub_80772DA
// .extern sub_807731C

.include "asm28.inc"
// .extern off_80CFF24

.include "asm27.inc"
// .extern sub_80A02AE

.include "asm00.inc"
// .extern f900_80009B4
// .extern sub_8000C98
// .extern sub_8001C94
// .extern sub_8001D60


/* Undeclared Symbols */
.equ LCDControl, 0x4000000

.endif // INC_ASM22
