.ifndef INC_ASM21
.equ INC_ASM21, 0

/* Public Interface */
.extern dword_808D348
.extern dword_808D638


/* External Symbols */
.include "start.inc"
// .extern start_

.include "asm28.inc"
// .extern off_80CFF24

.include "asm27.inc"
// .extern sub_80A2798

.include "asm00.inc"
// .extern sub_8001C94
// .extern sub_8001D60


/* Undeclared Symbols */
.equ byte_2010BA8, 0x2010BA8
.equ byte_2010BA9, 0x2010BA9
.equ off_8067880, 0x8067880
.equ off_80678F0, 0x80678F0
.equ off_8067960, 0x8067960
.equ off_80679B8, 0x80679B8
.equ off_8067A28, 0x8067A28
.equ off_8067AC8, 0x8067AC8

.endif // INC_ASM21
