.ifndef INC_ASM25
.equ INC_ASM25, 0

/* Public Symbols */
.extern dword_8097370


/* External Symbols */
.include "asm27.inc"
// .extern sub_80A6DB8
// .extern sub_80A6F0E
// .extern sub_80A6F18

.include "asm00.inc"
// .extern f500_8000558


/* Undeclared Symbols */
.equ unk_20005E0, 0x20005E0
.equ byte_20005E1, 0x20005E1
.equ word_20005E2, 0x20005E2
.equ word_20005E4, 0x20005E4

.endif // INC_ASM25
