.ifndef INC_MAIN
.equ INC_MAIN, 0

// Public Interface
.extern main_
.extern sub_8000538

// Forward Reference
.extern game_routine
.extern loc_800030C
.extern off_8000324
.extern off_8000328
.extern jt_mainCallbacks
.extern main_static_800036C
.extern loc_800036E
.extern loc_8000372
.extern off_8000390
.extern off_8000394
.extern off_8000398
.extern main_static_800039C
.extern loc_80003A2
.extern off_80003AC
.extern main_static_80003B0
.extern loc_80003BE
.extern loc_80003D4
.extern loc_80003EA
.extern loc_80003F4
.extern loc_80003FA
.extern loc_8000402
.extern off_8000414
.extern main_static_8000418
.extern loc_8000452
.extern locret_8000454
.extern main_static_8000456
.extern loc_800045C
.extern main_static_80004FC
.extern dword_8000528
.extern off_800052C
.extern dword_8000534
.extern dword_8000548


.endif // INC_MAIN
