.ifndef INC_START
.equ INC_START, 0

// Public Interface
.extern start_
.extern start_800025C
.extern start_8000284

// Forward Reference
.extern dword_8000004
.extern start_init
.extern start_static_80001B0
.extern loc_80001B4
.extern start_static80001C4
.extern dword_80001D8
.extern off_80001DC
.extern dword_80001E0
.extern dword_80001E4
.extern off_80001E8
.extern dword_80001EC
.extern off_80001F0
.extern dword_80001F4
.extern off_80001F8
.extern off_80001FC
.extern dword_8000200
.extern off_8000204
.extern off_8000208
.extern off_800020C
.extern off_8000210
.extern off_8000214
.extern off_8000218
.extern dword_800021C
.extern off_8000220
.extern off_8000224
.extern loc_800026A
.extern off_8000280
.extern off_8000294
.extern off_8000298


.endif // INC_START
